### ISSUE TITLE
Submit not working

### ISSUE THREAD

**Issue by Bosstjanz** [cybercraftit/user-frontend-for-elementor#2]
Hello,

I just made first form by your plugin but after pressing Submit button nothing happens. I am new in Elementor and your plugin so I will try to make one Elementor form and try if Elementor is making problems or your plugin.

Thank you for help.

Lp, Boštjan

**Comment by mithublue** [comment]
Hi, we are testing the issue and will fix it if found.

**Comment by mithublue** [comment]
New version is realeased. Please update your plugin to the latest version and hopefully the issue will be fixed
